kafka.bootstrapServers=localhost:9092
kafka.topic=adaptive-topic
kafka.groupId=adaptive-consumer-group

consumer.logPath=E:/UFS - Mestrado/SoftwaresGo/SoftwareAdaptativo/KafkaAdaptiveSystemDotNet/Consumer/self-adaptive-kafka-consumer/Logs/consumer_log.txt
consumer.initialMaxPollRecords=10
consumer.maxPollRecordsLimit=1000
consumer.fetchMaxBytes=1048576
consumer.fetchWaitMaxMs=500
consumer.logIntervalSeconds=1

monitor.sampleIntervalSeconds=60
monitor.readIntervalSeconds=60

controller.enabled=true
controller.kp=0.1
controller.ki=0.0009
controller.targetRate=50, 100, 150
controller.targetRateIntervalSeconds=600

benchmark.stepRecords=5
benchmark.stepIntervalSeconds=30
